Repository sassafrastech/madeline, pull requests merged in 2018-05, with the labels that each got.

#523 8359: removes migration, adds validations
  Gemfile
  Gemfile.lock
  app/controllers/admin/divisions_controller.rb
  app/models/division.rb
  config/initializers/friendly_id.rb
  db/migrate/20180410173704_update_division_with_short_name.rb
  db/migrate/20180501183741_change_division_public_default.rb
  db/migrate/20180501183920_set_divisions_to_private.rb
  db/schema.rb
  spec/factories/divisions.rb
  spec/models/division_spec.rb
Labels: complete

#526 8369: Update rails_html_sanitizer and other rails dependencies
  Gemfile.lock
Labels: complete, small-code-change

#529 8378 fix total_fixed_cost
  app/views/admin/loans/questionnaires/breakeven_rampup/_main.html.slim
Labels: complete, small-code-change

#535 8437: fixed loan public level defaults
  app/views/admin/loans/_form.html.slim
Labels: complete, high priority merge, small-code-change

#501 8004 determine txn type
  app/models/accounting/quickbooks/data_extractor.rb
  app/models/accounting/quickbooks/updater.rb
  app/models/accounting/transaction.rb
  lib/option_set_creator.rb
  spec/models/accounting/quickbooks/data_extractor_spec.rb
  spec/models/accounting/quickbooks/updater_spec.rb
Labels: high priority merge, needs-qa

#534 8340: Show loan descendants
  app/controllers/public/loans_controller.rb
  app/models/loan.rb
  app/policies/loan_policy.rb
  spec/features/loan_index_spec.rb
Labels: high priority merge, needs-qa
