Repository sassafrastech/madeline, pull requests merged in 2018-09, with the labels that each got.

#598 8847 make test expectation more specific
  spec/features/loan_index_spec.rb
Labels: complete

#601 8848: Add add link button color
  app/assets/stylesheets/admin/_summernote.scss
Labels: complete

#609 8838 remove duplicate before block method
  spec/models/accounting/quickbooks/data_extractor_spec.rb
Labels: complete

#613 disable and hide fields
  app/views/admin/documentations/_form.html.slim
Labels: ready-for-review

#611 8800: Fixes policies, makes docs division-based
  app/controllers/admin/admin_controller.rb
  app/controllers/admin/documentations_controller.rb
  app/controllers/concerns/documentable.rb
  app/helpers/admin_helper.rb
  app/models/documentation.rb
  app/policies/documentation_policy.rb
  db/migrate/20180917073415_add_division_to_documentations.rb
  db/schema.rb
  spec/factories/documentations.rb
  spec/features/admin/documentation_spec.rb
  spec/models/documentation_spec.rb
Labels: needs-qa

#610 8874: Improve translatable workaround
  app/assets/javascripts/summernote-init.js
  app/helpers/application_helper.rb
  app/helpers/translations_helper.rb
  app/views/admin/documentations/_form.html.slim
Labels: needs-qa

#614 8899: Fixes bug with missing inputs
  app/helpers/translations_helper.rb
Labels: complete, small-code-change
