Repository sassafrastech/madeline, pull requests merged in 2018-08, with the labels that each got.

#561 8691 summernote list extra space bug
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
Labels: complete

#570 8750: Fixes issue, updates old specs
  app/controllers/public/loans_controller.rb
  app/models/loan.rb
  app/policies/loan_policy.rb
  app/views/public/loans/show.html.slim
  spec/factories/loans.rb
  spec/features/loan_details_spec.rb
  spec/features/loan_index_spec.rb
  spec/policies/loan_policy_spec.rb
Labels: high priority merge

#573 8777 documentation model
  app/models/accounting/account.rb
  app/models/accounting/line_item.rb
  app/models/accounting/quickbooks/connection.rb
  app/models/accounting/transaction.rb
  app/models/application_record.rb
  app/models/country.rb
  app/models/currency.rb
  app/models/division.rb
  app/models/documentation.rb
  app/models/legacy/cooperative.rb
  app/models/legacy/division.rb
  app/models/legacy/due_diligence_per_loan_type.rb
  app/models/legacy/loan.rb
  app/models/legacy/loan_question.rb
  app/models/legacy/loan_response.rb
  app/models/legacy/loan_response_set.rb
  app/models/legacy/loan_responses_i_frame.rb
  app/models/legacy/loan_type.rb
  app/models/legacy/media.rb
  app/models/legacy/member.rb
  app/models/legacy/note.rb
  app/models/legacy/org_snapshot_data.rb
  app/models/legacy/project_event.rb
  app/models/legacy/project_log.rb
  app/models/legacy/translation.rb
  app/models/loan_health_check.rb
  app/models/loan_question_requirement.rb
  app/models/media.rb
  app/models/note.rb
  app/models/option.rb
  app/models/option_set.rb
  app/models/organization.rb
  app/models/person.rb
  app/models/progress_metric.rb
  app/models/project.rb
  app/models/project_log.rb
  app/models/question.rb
  app/models/question_set.rb
  app/models/repayment.rb
  app/models/response_set.rb
  app/models/role.rb
  app/models/timeline_entry.rb
  app/models/translation.rb
  app/models/user.rb
  config/initializers/active_record_base.rb
  db/migrate/20180820154353_create_documentations.rb
  db/migrate/20180820164459_make_html_identifier_unique.rb
  db/schema.rb
  spec/factories/documentations.rb
  spec/models/documentation_spec.rb
Labels: ready-for-review

#574 8791: Removes division dependency
  app/models/concerns/translatable.rb
Labels: complete

#581 8798 add page title to documentation
  app/controllers/admin/documentations_controller.rb
  app/models/documentation.rb
  app/views/admin/documentations/_form.html.slim
  config/locales/en/documentations.en.yml
  spec/features/admin/documentation_spec.rb
Labels: complete

#577 8779 edit documentation
  app/controllers/admin/documentations_controller.rb
  app/policies/documentation_policy.rb
  app/views/admin/documentations/_form.html.slim
  app/views/admin/documentations/edit.html.slim
  app/views/admin/documentations/show.html.slim
  config/locales/en/documentations.en.yml
  config/routes.rb
  spec/features/admin/documentation_spec.rb
Labels: ready-for-review

#582 8799 show documentation
  app/controllers/admin/documentations_controller.rb
  app/policies/documentation_policy.rb
  app/views/admin/documentations/show.html.slim
  config/routes.rb
  spec/features/admin/documentation_spec.rb
Labels: complete

#583 8781: Summernote support for translatable
  app/models/concerns/translatable.rb
  app/models/documentation.rb
  app/models/media.rb
  app/models/note.rb
  app/models/option.rb
  app/models/project.rb
  app/models/project_log.rb
  app/models/project_step.rb
  app/models/question.rb
  app/models/question_set.rb
  app/models/timeline_entry.rb
  app/models/translation.rb
  db/migrate/20180824150514_add_allow_html_to_translations.rb
  db/schema.rb
  spec/factories/translations.rb
  spec/models/translation_spec.rb
Labels: ready-for-review

#591 8835 bugfix popovers
  app/helpers/admin_helper.rb
Labels: complete, high priority merge
