Repository sassafrastech/madeline, pull requests merged in 2019-09, with the labels that each got.

#677 10012: adds to_csv
  app/models/data_export.rb
  config/locales/en/data_exports.en.yml
  spec/fixtures/data_export.csv
  spec/models/data_export_spec.rb
Labels: needs-minor-revision, non-develop merge

#676 10011: data export model, base controller
  app/controllers/admin/data_exports_controller.rb
  app/models/data_export.rb
  config/locales/en/data_exports.en.yml
  db/migrate/20190828052149_create_data_exports.rb
  db/schema.rb
  spec/factories/data_exports_factory.rb
  spec/fixtures/data_export.csv
  spec/models/data_export_spec.rb
Labels: has child merges, needs-minor-revision, non-develop merge

#679 10014: add DataExportService to process data and convert to csv
  app/services/data_export_service.rb
  spec/services/data_export_service_spec.rb
Labels: complete, non-develop merge

#681 10169: Remove hidden spacing from translations
  config/locales/en/loans.en.yml
Labels: complete
