Repository sassafrastech/madeline, pull requests merged in 2020-10, with the labels that each got.

#796 11155: enable cloud file uploads
  .env.example
  Gemfile
  Gemfile.lock
  app/models/division.rb
  app/models/media.rb
  app/uploaders/logo_uploader.rb
  app/uploaders/media_item_uploader.rb
  app/views/admin/divisions/_form.html.slim
  config/initializers/carrierwave.rb
  db/migrate/20201007160952_add_logo_to_divisions.rb
  db/schema.rb
  spec/models/division_spec.rb
Labels: needs-qa

#797 11130 txn modal ux improvements
  app/assets/stylesheets/admin/forms/_transaction_form.scss
  app/models/accounting/transaction.rb
  app/views/admin/accounting/transactions/_form.slim
  app/views/admin/accounting/transactions/_modal_content.slim
  spec/models/accounting/qb/journal_entry_extractor_spec.rb
Labels: non-develop merge, ready-for-review

#795 11135: update check building to use sync_token field instead of quick…
  app/assets/javascripts/admin/transaction_modal_view.coffee
  app/assets/stylesheets/admin/forms/_transaction_form.scss
  app/models/accounting/qb/transaction_builder.rb
  app/models/accounting/transaction.rb
  app/views/admin/accounting/transactions/_form.slim
  app/views/admin/accounting/transactions/_modal_content.slim
  config/locales/en/en.yml
  spec/features/admin/accounting/transaction_flow_spec.rb
  spec/models/accounting/qb/journal_entry_extractor_spec.rb
Labels: non-develop merge, ready-for-review

#794 11136 edit txn qa fixes
  app/assets/javascripts/admin/transaction_modal_view.coffee
  app/assets/stylesheets/admin/forms/_transaction_form.scss
  app/models/accounting/interest_calculator.rb
  app/models/accounting/qb/transaction_builder.rb
  app/models/accounting/qb/updater.rb
  app/models/accounting/transaction.rb
  app/views/admin/accounting/transactions/_form.slim
  app/views/admin/accounting/transactions/_modal_content.slim
  config/locales/en/en.yml
  spec/features/admin/accounting/transaction_flow_spec.rb
  spec/models/accounting/qb/journal_entry_extractor_spec.rb
Labels: ready-for-review

#798 Fix for flapping media spec
  spec/factories/media_factory.rb
  spec/support/assets/images/the_swing1.jpg
  spec/support/assets/images/the_swing2.jpg
  spec/support/modules/media_attachable_spec.rb
Labels: ready-for-review

#799 11153: Added email notification when jobs not running
  app/controllers/ping_controller.rb
Labels: complete

#801 11137: remove timeline list
  app/controllers/admin/basic_projects_controller.rb
  app/controllers/admin/loans_controller.rb
Labels: ready-for-review

#804 11197: Add version number to ping page
  app/helpers/application_helper.rb
  app/views/ping/index.text.erb
Labels: ready-for-review

#800 11175: purchases can now be managed - have to check doc number when e…
  app/models/accounting/qb/journal_entry_extractor.rb
  app/models/accounting/qb/purchase_extractor.rb
  app/models/accounting/qb/transaction_extractor.rb
  spec/models/accounting/qb/bill_extractor_spec.rb
  spec/models/accounting/qb/purchase_extractor_spec.rb
Labels: needs-qa

#805 11195 txn modal js glitches
  app/assets/javascripts/admin/transactions_view.coffee
  app/views/admin/accounting/transactions/_modal.slim
Labels: needs-qa

#803 11102: run update at end of full fetcher
  app/models/accounting/qb/full_fetcher.rb
  spec/models/accounting/qb/full_fetcher_spec.rb
Labels: needs-qa

#802 11182 preserve division dept assoc thru qb reset
  app/models/accounting/qb/full_fetcher.rb
  spec/models/accounting/qb/full_fetcher_spec.rb
Labels: needs-qa
