Repository sassafrastech/madeline, pull requests merged in 2020-06, with the labels that each got.

#763 10816: Ensure user must choose action to exit from modal
  app/views/admin/loans/questionnaires/_rich_text_modal.html.slim
Labels: complete

#766 10841 rich text bug fix
  app/assets/javascripts/admin/loan_questionnaires_view.coffee
  app/assets/javascripts/admin/rich_text_modal_view.coffee
  app/views/admin/loans/questionnaires/_answer.html.slim
Labels: complete

#770 8369: security updates
  Gemfile.lock
Labels: complete

#771 10858: performance monitoring
  .gitignore
  Gemfile
  Gemfile.lock
  config/scout_apm.yml.example
Labels: complete, non-develop merge

#762 10805: move attachment col back all the way right
  app/views/admin/data_exports/_data_exports_grid_definition.html.slim
Labels: complete

#767 10806: question numbering
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/models/question.rb
  app/views/admin/loans/questionnaires/_questionnaire_toc.html.slim
  lib/romanize.rb
  spec/models/question_spec.rb
Labels: complete

#768 10858 error monitoring
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/application.rb
  config/initializers/sentry.rb
  config/scout_apm.yml.example
Labels: complete, has child merges
