Repository sassafrastech/madeline, pull requests merged in 2020-12, with the labels that each got.

#811 11251 all disb as purchases
  app/controllers/concerns/transaction_controllable.rb
  app/models/accounting/interest_calculator.rb
  app/models/accounting/qb/purchase_extractor.rb
  app/models/accounting/qb/transaction_builder.rb
  app/models/accounting/qb/transaction_extractor.rb
  app/models/accounting/qb/transaction_reconciler.rb
  app/models/accounting/transaction.rb
  app/views/admin/accounting/transactions/_form.slim
  config/locales/en/transactions.en.yml
  spec/models/accounting/qb/purchase_extractor_spec.rb
  spec/models/accounting/transaction_spec.rb
Labels: needs-qa

#816 11254 txn modal edit new bug
  app/assets/javascripts/admin/transaction_modal_view.coffee
  app/assets/javascripts/admin/transactions_view.coffee
Labels: complete

#818 11345 change cash label to wire or credit card
  app/models/accounting/transaction.rb
  config/locales/en/transactions.en.yml
Labels: complete, non-develop merge

#819 11389: Fix file naming crash in data exports
  app/models/data_export.rb
Labels: bug-fix, complete, tiny-pr
