Repository sassafrastech/madeline, pull requests merged in 2020-11, with the labels that each got.

#806 11169: add questionnaire numeric answers to standard data export
  app/models/data_export.rb
  app/models/enhanced_loan_data_export.rb
  app/views/admin/data_exports/choose_type.html.slim
  config/locales/en/data_exports.en.yml
  spec/features/admin/data_export_flow_spec.rb
  spec/models/standard_loan_data_export_spec.rb
Labels: needs-qa

#808 11208: documentation index
  app/assets/stylesheets/admin/_documentation.scss
  app/assets/stylesheets/admin/loans/_criteria.scss
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/controllers/admin/documentations_controller.rb
  app/helpers/documentations_helper.rb
  app/policies/documentation_policy.rb
  app/views/admin/documentations/index.html.slim
  app/views/layouts/admin/_site_menu.html.slim
  config/locales/en/controllers.en.yml
  config/locales/en/documentations.en.yml
  config/locales/en/en.yml
  spec/policies/documentation_policy_spec.rb
  spec/support/modules/base_policy.rb
Labels: ready-for-review

#807 11255: ensure doc number always updated when writing to qb
  app/models/accounting/qb/transaction_builder.rb
Labels: complete, question

#809 11285 enhanced data export crash
  app/models/enhanced_loan_data_export.rb
Labels: ready-for-review

#810 11048: Move update button
  app/assets/stylesheets/admin/_general.scss
  app/controllers/admin/accounting/quickbooks_controller.rb
  app/controllers/admin/accounting/transactions_controller.rb
  app/jobs/fetch_quickbooks_changes_job.rb
  app/models/accounting/qb/updater.rb
  app/policies/accounting/quickbooks_policy.rb
  app/views/admin/loans/index.html.slim
  app/views/admin/project_steps/_show.html.slim
  app/views/admin/settings/index.html.slim
  app/views/admin/tasks/show.html.slim
  config/locales/en/en.yml
  config/locales/en/loans.en.yml
  config/locales/en/settings.en.yml
  config/locales/en/task.en.yml
  config/routes.rb
Labels: complete

#813 11266: edit documentations
  Gemfile.lock
  app/controllers/admin/documentations_controller.rb
  app/models/accounting/customer.rb
  app/models/accounting/problem_loan_transaction.rb
  app/models/accounting/qb/department.rb
  app/models/accounting/qb/vendor.rb
  app/models/data_export.rb
  app/models/documentation.rb
  app/models/enhanced_loan_data_export.rb
  app/models/standard_loan_data_export.rb
  app/models/task.rb
  app/views/admin/documentations/_form.html.slim
  app/views/admin/documentations/index.html.slim
  db/migrate/20201114111327_remove_previous_url_from_documentations.rb
  db/schema.rb
  lib/tasks/auto_annotate_models.rake
  spec/factories/accounting_customers_factory.rb
  spec/factories/accounting_qb_connections_factory.rb
  spec/factories/accounting_qb_departments_factory.rb
  spec/factories/accounting_qb_vendors_factory.rb
  spec/factories/accounting_transactions_factory.rb
  spec/factories/countries_factory.rb
  spec/factories/data_exports_factory.rb
  spec/factories/divisions_factory.rb
  spec/factories/documentations_factory.rb
  spec/factories/organizations_factory.rb
  spec/factories/questions_factory.rb
  spec/factories/tasks_factory.rb
  spec/models/accounting/customer_spec.rb
  spec/models/accounting/qb/department_spec.rb
  spec/models/accounting/qb/vendor_spec.rb
  spec/models/data_export_spec.rb
  spec/models/documentation_spec.rb
  spec/models/standard_loan_data_export_spec.rb
  spec/models/task_spec.rb
Labels: complete

#812 11253 balances not calced for some loans
  app/models/accounting/qb/updater.rb
  app/views/admin/accounting/transactions/_form.slim
  spec/models/accounting/qb/updater_spec.rb
Labels: complete
