Repository sassafrastech/madeline, pull requests merged in 2021-01, with the labels that each got.

#821 11301: set txn description to match first line item description in tx…
  app/models/accounting/qb/transaction_extractor.rb
Labels: complete

#822 11384: add rbenv_rake job type that inits rbenv vars and use in staging
  config/schedule.rb
Labels: complete

#823 11350 biz plan outline AND 11369 optional qs biz plan tree
  app/assets/javascripts/admin/loan_questionnaires_view.coffee
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/assets/stylesheets/admin/questions/_questions.scss
  app/views/admin/loans/_questions.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_form.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_outline.html.slim
  config/locales/en/loans.en.yml
Labels: complete, needs-qa

#824 11368: use 'user_created' to determine if txn coming from m…
  app/models/accounting/transaction.rb
  spec/features/admin/accounting/transaction_flow_spec.rb
  spec/models/accounting/transaction_spec.rb
Labels: complete, tiny-pr

#825 11378: fix respect_closed_book_date validation and set user_created i…
  app/controllers/admin/accounting/transactions_controller.rb
  app/models/accounting/transaction.rb
Labels: needs-minor-revision, tiny-pr

#826 11412 null account on li error
  app/models/accounting/qb/bill_extractor.rb
  app/models/accounting/qb/deposit_extractor.rb
  app/models/accounting/qb/purchase_extractor.rb
  app/models/accounting/qb/transaction_extractor.rb
Labels: complete, tiny-pr

#828 11404 status lights
  app/assets/stylesheets/admin/_colors.scss
  app/assets/stylesheets/admin/_progress_bars.scss
  app/views/admin/loans/_form.html.slim
  app/views/admin/loans/questionnaires/_progress.html.slim
  app/views/admin/loans/questionnaires/_progress_bar.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
  config/locales/en/questions.en.yml
Labels: complete

#827 11349: media gallery
  app/assets/stylesheets/admin/media/_media.scss
  app/controllers/admin/media_controller.rb
  app/controllers/admin/project_logs_controller.rb
  app/controllers/admin/projects_controller.rb
  app/helpers/media_helper.rb
  app/models/project_log.rb
  app/views/admin/media/_media_box.html.slim
  app/views/admin/media/_media_item.html.slim
  app/views/admin/media/index.html.slim
  app/views/layouts/admin/_site_menu.html.slim
  config/initializers/bullet.rb
  config/locales/en/en.yml
  config/locales/en/media.en.yml
  config/locales/en/project_logs.en.yml
  config/routes.rb
  lib/tasks/fake_data.rake
  spec/factories/media_factory.rb
Labels: ready-for-review

#831 11349: make num cols responsive in media gallery
  app/assets/stylesheets/admin/media/_media.scss
  app/controllers/admin/media_controller.rb
Labels: ready-for-review
