Repository sassafrastech/madeline, pull requests merged in 2021-02, with the labels that each got.

#834 11407: display notice if reqd q has no answer in view mode
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/assets/stylesheets/admin/questions/_questions.scss
  app/assets/stylesheets/admin/questions/_questions_outline.scss
  app/views/admin/loans/questionnaires/_answer.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_form.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_outline.html.slim
  app/views/layouts/admin/_custom_colors.html.slim
  config/locales/en/loans.en.yml
  config/locales/en/questions.en.yml
Labels: ready-for-review

#832 11330 AND 11405 edit mode logic 2
  app/assets/javascripts/admin/loan_questionnaires_view.coffee
  app/assets/javascripts/admin/rich_text_modal_view.coffee
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/assets/stylesheets/admin/questions/_questions.scss
  app/assets/stylesheets/admin/questions/_questions_outline.scss
  app/views/admin/loans/_questions.html.slim
  app/views/admin/loans/questionnaires/_answer.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_form.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_outline.html.slim
  app/views/layouts/admin/_custom_colors.html.slim
  config/locales/en/loans.en.yml
  config/locales/en/questions.en.yml
Labels: ready-for-review

#833 11433 improve biz plan loading time
  app/controllers/concerns/questionnaire_renderable.rb
  app/models/filtered_question.rb
  app/models/loan_filtered_question.rb
Labels: ready-for-review

#835 11406 biz planning viz updates
  VERSION
  app/assets/javascripts/admin/loan_questionnaires_view.coffee
  app/assets/stylesheets/admin/loans/_questionnaires.scss
  app/assets/stylesheets/admin/media/_media.scss
  app/controllers/admin/media_controller.rb
  app/controllers/admin/project_logs_controller.rb
  app/controllers/admin/projects_controller.rb
  app/controllers/concerns/questionnaire_renderable.rb
  app/helpers/media_helper.rb
  app/models/filtered_question.rb
  app/models/loan_filtered_question.rb
  app/models/project_log.rb
  app/views/admin/loans/questionnaires/_answer.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
  app/views/admin/media/_media_box.html.slim
  app/views/admin/media/_media_item.html.slim
  app/views/admin/media/index.html.slim
  app/views/layouts/admin/_site_menu.html.slim
  config/initializers/bullet.rb
  config/locales/en/en.yml
  config/locales/en/media.en.yml
  config/locales/en/project_logs.en.yml
  config/routes.rb
  lib/tasks/fake_data.rake
  spec/factories/media_factory.rb
Labels: needs-qa

#838 11413: Logs Landing Page - First Draft
  app/assets/javascripts/admin/log_form_modal_view.coffee
  app/assets/javascripts/admin/log_list_view.coffee
  app/controllers/admin/project_logs_controller.rb
  app/views/admin/project_logs/_log.html.slim
  app/views/admin/project_logs/_log_list.html.slim
  app/views/admin/project_logs/show.html.slim
Labels: needs-minor-revision

#839 11413: fix logs show bug
  app/views/admin/project_logs/show.html.slim
Labels: complete

#842 11413: change log titles
  config/locales/en/project_logs.en.yml
Labels: complete, enhancement, tiny-pr
