Repository sassafrastech/madeline, pull requests merged in 2021-09, with the labels that each got.

#913 11840 catch error improve reporting
  app/controllers/admin/accounting/transactions_controller.rb
  app/jobs/quickbooks_update_job.rb
  app/models/accounting/qb/annotated_intuit_request_exception.rb
  app/models/accounting/qb/error_handler.rb
  app/models/accounting/qb/transaction_reconciler.rb
  config/locales/en/en.yml
Labels: ready-for-review

#923 11961: Remove representative field/column
  app/controllers/admin/loans_controller.rb
  app/models/loan.rb
  app/models/person.rb
  app/views/admin/loans/_form.html.slim
  app/views/admin/loans/_loans_grid_definition.html.slim
  config/locales/en/en.yml
  db/migrate/20210922194332_remove_representative_from_projects.rb
  db/schema.rb
  spec/factories/loans_factory.rb
Labels: complete

#925 Add legacy_id to response_sets and questions
  db/migrate/20210927155210_add_legacy_id_to_response_sets_and_questions.rb
  db/schema.rb
Labels: question, complete

#924 11963: Add sort order for logs on step modal
  app/models/timeline_entry.rb
Labels: complete

#922 11959 add byte order mark
  Gemfile
  Gemfile.lock
  app/models/data_export.rb
  spec/models/data_export_spec.rb
  spec/models/wice_spreadsheet_spec.rb
Labels: question, complete

#918 Feature/11890 division question sets (phase 3)
  app/assets/javascripts/admin/application_view.coffee
  app/assets/javascripts/admin/popover_view.coffee
  app/assets/javascripts/admin/questions_view.coffee
  app/assets/stylesheets/admin/_tree.scss
  app/assets/stylesheets/admin/loans/_criteria.scss
  app/assets/stylesheets/admin/questionnaires/_questionnaire.scss
  app/assets/stylesheets/admin/questionnaires/_questionnaire_form.scss
  app/assets/stylesheets/admin/questionnaires/_questionnaires.scss
  app/assets/stylesheets/admin/questions/_manage.scss
  app/assets/stylesheets/admin/questions/_misc.scss
  app/controllers/admin/loans_controller.rb
  app/controllers/admin/questions_controller.rb
  app/controllers/admin/response_sets_controller.rb
  app/controllers/concerns/questionnaire_renderable.rb
  app/models/division.rb
  app/models/loan.rb
  app/models/loan_filtered_question.rb
  app/models/loan_health_check.rb
  app/models/project.rb
  app/models/question.rb
  app/models/question_set.rb
  app/models/response_set.rb
  app/serializers/filtered_question_serializer.rb
  app/views/admin/loans/_questions.html.slim
  app/views/admin/loans/print.html.slim
  app/views/admin/loans/questionnaires/_criteria.html.slim
  app/views/admin/loans/questionnaires/_questionnaire_form.html.slim
  app/views/admin/questions/index.html.slim
  app/views/layouts/admin/_site_menu.html.slim
  app/views/layouts/admin/main.html.slim
  config/locales/en/questions.en.yml
  db/migrate/20210907194740_ensure_max_one_root_per_question_set.rb
  db/migrate/20210907201954_add_division_to_question_sets.rb
  db/migrate/20210908204646_add_loan_prefix_to_response_set_kinds.rb
  db/migrate/20210908205109_rename_question_sets_internal_name_to_kind.rb
  db/migrate/20210909122805_remove_response_set_duplicates.rb
  db/migrate/20210909142344_add_question_set_to_response_sets.rb
  db/migrate/20210909185709_update_response_sets_unique_key.rb
  db/migrate/20210909190131_remove_kind_from_response_sets.rb
  db/migrate/20210910164556_convert_to_jsonb.rb
  db/migrate/20210910170107_add_response_sets_loans_foreign_key.rb
  db/migrate/20210910173032_add_loan_question_requirements_foreign_key.rb
  db/migrate/20210910180420_copy_root_questions_to_top_level_divisions.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/loans_factory.rb
  spec/factories/question_sets_factory.rb
  spec/factories/questions_factory.rb
  spec/factories/response_sets_factory.rb
  spec/jobs/recalculate_loan_health_job_spec.rb
  spec/models/loan_health_check_spec.rb
  spec/models/project_duplicator_spec.rb
  spec/models/question_mover_spec.rb
  spec/models/question_set_spec.rb
  spec/support/helpers/question_spec_helpers.rb
  spec/system/admin/questionnaire_spec.rb
  spec/system/admin/questions_flow_spec.rb
Labels: complete

#921 11958: Add inception field
  app/controllers/admin/organizations_controller.rb
  app/models/organization.rb
  app/views/admin/organizations/_form.html.slim
  app/views/admin/organizations/_organizations_grid_definition.html.slim
  config/locales/en/database.en.yml
  config/locales/en/en.yml
  db/migrate/20210920172500_add_inception_to_organizations.rb
  db/migrate/20210928153001_migrate_and_remove_old_is_recovered_field.rb
  db/schema.rb
  lib/option_set_creator.rb
  spec/system/admin/organization_flow_spec.rb
Labels: needs-minor-revision
